version: '3'
services: 
  mongo:
    image: bitnami/mongodb
    restart: always
    environment:
      MONGODB_ROOT_PASSWORD: password123
      ALLOW_EMPTY_PASSWORD: 'true'
      MONGODB_DATABASE: scg-testing-data
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password123
    volumes: 
      - mongodb_data:/bitnami
  mongo-express:
    image: mongo-express
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
    ports:
      - 8081:8081
    depends_on:
      - mongo
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes: 
      - /app/node_modules
      - ./client:/app
    environment: 
      REACT_APP_API_HOST: http://localhost:3001
    depends_on:
      - api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 3001:3001
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      NODE_ENV: development
      PASSWORD_SALT: mysupersecret
      TOKEN_SECRET: MY_SECRET_KEY
      MONGO_DATABASE: scg-testing-data
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password123
    depends_on:
      - mongo
  map-worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./map-worker
    volumes: 
      - /app/node_modules
      - ./map-worker:/app
    environment:
      MONGO_DATABASE: scg-testing-data
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password123
      GOOGLE_API_KEY: AIzaSyC8iaDOAP3SpcjlOts_3cnqL8BWi51yL3o
    depends_on:
      - mongo
volumes:
  mongodb_data:
    driver: local