version: '3'
services: 
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./client:/app
    ports:
      - '80:80'
    environment: 
      REACT_APP_API_HOST: https://gentle-caverns-48044.herokuapp.com
    depends_on:
      - api
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      PASSWORD_SALT: mysupersecret
      TOKEN_SECRET: MY_SECRET_KEY
      MONGO_DATABASE: test
      MONGO_USERNAME: sa
      MONGO_PASSWORD: EfV2GPSZYCW8Ece
      CHANNEL_ACCESS_TOKEN: N689f+MD0f2+XiywAtNF4LiA5ZW23p61GQYvphsoKh15lL6kniso7ow6CCrsHSh230eJ4ndDS0vQUV5Ubou7Uif9jfyzHhVIKLJ0L3NOCZZVl87LwrTYZMYDmEkhe/UtMO2XtOT0RLQ1c9hTKn/puAdB04t89/1O/w1cDnyilFU=
      CHANNEL_SECRET: 84631887f660c5bc7e18d0c3565c8c70
  # map-worker:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./map-worker
  #   volumes: 
  #     - /app/node_modules
  #     - ./map-worker:/app
  #   environment:
  #     MONGO_DATABASE: test
  #     MONGO_USERNAME: sa
  #     MONGO_PASSWORD: EfV2GPSZYCW8Ece
  #     GOOGLE_API_KEY: AIzaSyC8iaDOAP3SpcjlOts_3cnqL8BWi51yL3o