#ifndef certs_h
#define certs_h

// Amazon's root CA. This should be the same for everyone.
const char AWS_CERT_CA[] = "-----BEGIN CERTIFICATE-----\n"
                           "MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\n"
                           "ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\n"
                           "b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\n"
                           "MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\n"
                           "b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\n"
                           "ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\n"
                           "9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\n"
                           "IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\n"
                           "VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\n"
                           "93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\n"
                           "jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\n"
                           "AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\n"
                           "A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\n"
                           "U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\n"
                           "N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\n"
                           "o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\n"
                           "5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\n"
                           "rqXRfboQnoZsG4q5WTP468SQvvG5\n"
                           "-----END CERTIFICATE-----\n";

// The private key for your device
const char AWS_CERT_PRIVATE[] = "-----BEGIN RSA PRIVATE KEY-----\n"
                                "MIIEogIBAAKCAQEA3r+CHFXebnJcC0rDhSUYvcWAdy2009TW2dTxpFy2UKKMxJiG\n"
                                "FF5rHW6ZMoWn5MeIK0etLS9UcXntPY07m3dtUm62KNwMWvafZzvUTGNOQC/L2NdZ\n"
                                "e4lOxvE3m2nkRZyF9sfqZVLUhHfQ/UyCd0hvGesbf/0/Xpq0pn+6NsOb4p2d3p3L\n"
                                "MXxnZULiG/ogToz0EaGtx+NQhbsUWGRabzLSdcyPMZBA72g5PifweDmuksdVvvV8\n"
                                "S/+f7oZEw1jmPPgKzxF+PoohRaFBuS+GGe2+j+yY66ogOhia06fzGCSHIkSAY49S\n"
                                "XMVtlztccDUU5X4stg/4RRWnFnsdqwEdCNxgcwIDAQABAoIBABuu72u4HFHbsqbQ\n"
                                "nuYgSyfisOme65dcH2upNHL59sqkuRwB3MART/yzbyTBSbF8PucqHFK+TB9iSOLa\n"
                                "d6sFt7eD/O2tE3gGqJ7655Kq0OHXTt1fPkbFNN4ywnd1PKKOJnQaOn5nQfRIs9eX\n"
                                "N6u9e9lbx+orPkHytjrvKuR9gRUzyB8dlhcXYHSUbyaI0O2KB9NMwogKqiWrodYk\n"
                                "5Q2FvM7GGhNmvL9pUmRhplr9jOEjDQt8HPHZvaxjbRpg/VnrviexIGoQ39INtr+n\n"
                                "cfJYhMKCI+CneV5IwUB5PRgtpTS1WoqrBOpEWfyKuJJIdldLesehE9dubhTCGGiE\n"
                                "GhWlMkkCgYEA/jJoBusxA08RpFOaydjpxgORDfkxegsLOS95CNnaebSW8kWrweEU\n"
                                "1trGEG3/Jpw4Z87JWNHiwApnALdurXJyOuLzCh5nCDzAB6mpBCWoiaigUAl67iko\n"
                                "ZsiwzhLRE0740VBrKroBAKRScTZllsLQMLtGfMN0MfKLCSB2sUNzzz0CgYEA4FP+\n"
                                "iYKQLL0/fN1GTf5cUxHJaI8i6w46Unn0fXp6kF7NzadxdOY3659RkjLG1xVEl0yi\n"
                                "riYT9px1NllbOOttY3FP08sb52CFrS2pOCGD8DIrDPvaFN//Vfr7vzx+kBHzOyi3\n"
                                "WywsGzOyakReu4bKdTP2mgJcW4zYwPLflAqT6W8CgYBAOxxuIx/PZjte+oEyX80y\n"
                                "a9RLY5xM6l17pbM/uUyrVCaQMWqlIurRH5bMr/65EuBt2qKl/uL9A6PjWnZs/W4/\n"
                                "0vj2pZgDTNZ5GTXMBnf/0MwxbTPS2jOLRUrnx3ltF5dnzJpHwZhfQSZT1Rr2bWON\n"
                                "7MRy4jCKLm9TbxCO2ix5QQKBgEdR7QcC/5t5v4mPQB7j066FZSdc+pkIuPon09dg\n"
                                "7T6hJYVQyv2DhBvhVynIAve2x0vjDYWYjZhGPe29kwcRsoF/MQYA+Soiwd1BOx+h\n"
                                "aDUhfhZuq/MfFCrd1NQEA6kCS/ZvB3xxGsS7NuoaOpQcUpnYn3pvbbWdnfwaO4Lx\n"
                                "qfz5AoGAIiWAl0V3odlILfvmTpF5PwfrtrJfrh7wk79liwSISBdyweABAkiBYXL+\n"
                                "hmGr5y6vNvLppk5ecYiwEqjh7wUeSdU8kTmFmteME78xsmjWZzweZg86dKEzKySA\n"
                                "TO4ooG1TM6IVgBOkxXwI/GxomEs7/gb8btxBF2HQkfeP1SdYI2k=\n"
                                "-----END RSA PRIVATE KEY-----\n";

// The certificate for your device
const char AWS_CERT_CRT[] = "-----BEGIN CERTIFICATE-----\n"
                            "MIIDWTCCAkGgAwIBAgIUInzsqeoSC16cEoOdmmP0hXiyPAYwDQYJKoZIhvcNAQEL\n"
                            "BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g\n"
                            "SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTE5MTEyMzE5NDUz\n"
                            "MloXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0\n"
                            "ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAN6/ghxV3m5yXAtKw4Ul\n"
                            "GL3FgHcttNPU1tnU8aRctlCijMSYhhReax1umTKFp+THiCtHrS0vVHF57T2NO5t3\n"
                            "bVJutijcDFr2n2c71ExjTkAvy9jXWXuJTsbxN5tp5EWchfbH6mVS1IR30P1MgndI\n"
                            "bxnrG3/9P16atKZ/ujbDm+Kdnd6dyzF8Z2VC4hv6IE6M9BGhrcfjUIW7FFhkWm8y\n"
                            "0nXMjzGQQO9oOT4n8Hg5rpLHVb71fEv/n+6GRMNY5jz4Cs8Rfj6KIUWhQbkvhhnt\n"
                            "vo/smOuqIDoYmtOn8xgkhyJEgGOPUlzFbZc7XHA1FOV+LLYP+EUVpxZ7HasBHQjc\n"
                            "YHMCAwEAAaNgMF4wHwYDVR0jBBgwFoAU/7oOBmsS+ccWVN9C0pKWSTMCcqMwHQYD\n"
                            "VR0OBBYEFE7oUB4N1LnkBVYanuOnN4U7y5mwMAwGA1UdEwEB/wQCMAAwDgYDVR0P\n"
                            "AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQAbefqyGpdhrpFKATqY8XaBq5cm\n"
                            "EE/B3MLFOI2UB2e6/ne4gksNgbDVu1hW41DyLN+8aXqxtJgdomM5UxnZB/6aTwVE\n"
                            "W8KJdLWFPedpplwUYOqlwp6BLU47kbpY7Eqn0oEJYiR0nsXY4x55440Djze6xfKs\n"
                            "ll5jw7P8naYhjGSMNaonKtUZehrnQBwa+syAAG7qTH69QmpLdA+2l4mlNyZPYQ3+\n"
                            "sLQmocMqQ8cXyDvjyz3UWM+j1BKnMqZ7wsQuHMTMg2ZdU0xikSUnTU4tB+V3Lc/a\n"
                            "t2grAFJuzqK6ZCn+rlHhdshCyV6BGFe3Jb0UU6TyKamv8MLvDVAR3EIbJUdO\n"
                            "-----END CERTIFICATE-----\n";

#endif